In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('Advertising.csv')
df.head() 

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [3]:
x=df.iloc[:,:-1]    
x

Unnamed: 0     TV  Radio  Newspaper
0             1  230.1   37.8       69.2
1             2   44.5   39.3       45.1
2             3   17.2   45.9       69.3
3             4  151.5   41.3       58.5
4             5  180.8   10.8       58.4
..          ...    ...    ...        ...
195         196   38.2    3.7       13.8
196         197   94.2    4.9        8.1
197         198  177.0    9.3        6.4
198         199  283.6   42.0       66.2
199         200  232.1    8.6        8.7

[200 rows x 4 columns]

In [5]:
y=df.iloc[:,-1:]
y

Sales
0     22.1
1     10.4
2      9.3
3     18.5
4     12.9
..     ...
195    7.6
196    9.7
197   12.8
198   25.5
199   13.4

[200 rows x 1 columns]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=100)

In [12]:
y_train

Sales
168   17.1
112   14.1
171   14.5
181   12.2
7     13.2
..     ...
87    16.0
103   14.7
67    13.4
24     9.7
8      4.8

[160 rows x 1 columns]

In [15]:
print(x_test.shape)
print(y_test.shape)

(40, 4)
(40, 1)


In [16]:
print(x_train.shape)
print(y_train.shape)

(160, 4)
(160, 1)


In [18]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm = lm.fit(x_train,y_train)     #lm.fit(input,output)
lm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
lm.coef_

array([[-0.00051964,  0.04559816,  0.18562488,  0.00208323]])

In [20]:
lm.intercept_

array([2.87235034])

In [21]:
y_pred=lm.predict(x_test)
y_pred

array([[10.48824161],
       [20.05724453],
       [16.82143569],
       [19.09208751],
       [20.93730253],
       [13.22041472],
       [11.86658311],
       [12.49411992],
       [20.53530472],
       [20.92725284],
       [10.87064977],
       [19.42243267],
       [ 6.4598072 ],
       [15.29161663],
       [ 9.0273649 ],
       [ 7.99176462],
       [16.21781083],
       [12.06186549],
       [17.08884053],
       [11.31403977],
       [17.11936948],
       [ 9.85756594],
       [20.7384262 ],
       [17.20189183],
       [15.19647914],
       [21.95287722],
       [19.13758165],
       [10.098652  ],
       [19.38317465],
       [14.86950178],
       [14.28208526],
       [ 7.71251361],
       [ 9.97144518],
       [14.7914838 ],
       [ 7.25498055],
       [13.64628787],
       [ 7.62827761],
       [11.80526556],
       [13.58085939],
       [15.18959199]])

In [22]:
y_test

Sales
126    6.6
104   20.7
99    17.2
92    19.4
111   21.8
167   12.2
116   12.2
96    11.7
52    22.6
69    22.3
164   11.9
124   19.7
182    8.7
154   15.6
125   10.6
196    9.7
194   17.3
177   11.7
163   18.0
31    11.9
11    17.4
73    11.0
15    22.4
41    17.1
97    15.5
128   24.7
133   19.6
82    11.3
139   20.7
123   15.2
83    13.6
65     9.3
151   11.6
162   14.9
170    8.4
77    14.2
32     9.6
173   11.7
174   11.5
85    15.2

In [24]:
y_pred.shape

(40, 1)

In [26]:
y_error = y_test - y_pred
y_error

Sales
126 -3.888242
104  0.642755
99   0.378564
92   0.307912
111  0.862697
167 -1.020415
116  0.333417
96  -0.794120
52   2.064695
69   1.372747
164  1.029350
124  0.277567
182  2.240193
154  0.308383
125  1.572635
196  1.708235
194  1.082189
177 -0.361865
163  0.911159
31   0.585960
11   0.280631
73   1.142434
15   1.661574
41  -0.101892
97   0.303521
128  2.747123
133  0.462418
82   1.201348
139  1.316825
123  0.330498
83  -0.682085
65   1.587486
151  1.628555
162  0.108516
170  1.145019
77   0.553712
32   1.971722
173 -0.105266
174 -2.080859
85   0.010408

In [27]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)   #shows how many times its giving results accurately

0.9184136004105717

In [28]:
coefficients = pd.concat([pd.DataFrame(x_train.columns),pd.DataFrame(np.transpose(lm.coef_))],axis=1)
coefficients

0         0
0  Unnamed: 0 -0.000520
1          TV  0.045598
2       Radio  0.185625
3   Newspaper  0.002083